// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826232147_AddMaintenanceSystem")]
    partial class AddMaintenanceSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.ConstantValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ElectrcityPricePerKiloWatt")
                        .HasColumnType("float");

                    b.Property<double>("FeesPerCubicMetter")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ConstantValues", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CriticalValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActiveForce")
                        .HasColumnType("float");

                    b.Property<double>("CenterAngle")
                        .HasColumnType("float");

                    b.Property<double>("CuttingForce")
                        .HasColumnType("float");

                    b.Property<double>("CuttingMoment")
                        .HasColumnType("float");

                    b.Property<double>("EnterAngle")
                        .HasColumnType("float");

                    b.Property<double>("FrictionAngle")
                        .HasColumnType("float");

                    b.Property<double>("FrictionCorrectionCofficient")
                        .HasColumnType("float");

                    b.Property<double>("FrictionForceOnRake")
                        .HasColumnType("float");

                    b.Property<double>("LeavingAngle")
                        .HasColumnType("float");

                    b.Property<double>("NormalForceToRake")
                        .HasColumnType("float");

                    b.Property<double>("NormalForceToShear")
                        .HasColumnType("float");

                    b.Property<double>("ShearAngle")
                        .HasColumnType("float");

                    b.Property<double>("ShearForce")
                        .HasColumnType("float");

                    b.Property<double>("StadiedTheta")
                        .HasColumnType("float");

                    b.Property<double>("ThrustForce")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CriticalValues", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumedLife")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ElementInformationId")
                        .HasColumnType("int");

                    b.Property<bool>("FailureDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ImageOfElementAtMachine")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderOfElementAtMachine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementInformationId")
                        .IsUnique();

                    b.HasIndex("OrderOfElementAtMachine")
                        .IsUnique();

                    b.ToTable("Elements", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.ElementInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catalog")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("DefaultLife")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LifeUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ElementsInformation", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<double>("ElementPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("StoppingTimeCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("MaintenanceDate");

                    b.ToTable("Maintenance", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.OperationCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumedElectricity")
                        .HasColumnType("float");

                    b.Property<double>("CuttingSpeed")
                        .HasColumnType("float");

                    b.Property<double>("FeedRate")
                        .HasColumnType("float");

                    b.Property<double>("SheftSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OperationConditions", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.OperationsProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalValuesId")
                        .HasColumnType("int");

                    b.Property<int>("OperationConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("WoodTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriticalValuesId")
                        .IsUnique();

                    b.HasIndex("OperationConditionId")
                        .IsUnique();

                    b.HasIndex("ProductionConditionId")
                        .IsUnique();

                    b.HasIndex("WoodTypeId");

                    b.ToTable("OperationsProcesses", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.ProductionCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductHeight")
                        .HasColumnType("int");

                    b.Property<int>("ProductWidth")
                        .HasColumnType("int");

                    b.Property<double>("ProductionVolume")
                        .HasColumnType("float");

                    b.Property<double>("TotalFees")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductionConditions", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.WoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CoefficientOfFriction")
                        .HasColumnType("float");

                    b.Property<double>("ShearYieldStressInMpa")
                        .HasColumnType("float");

                    b.Property<double>("SpecificWorkToSurfaceSeparationJoulPerMeter2")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Category")
                        .IsUnique();

                    b.ToTable("WoodTypes", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Element", b =>
                {
                    b.HasOne("DataAccess.Entities.ElementInformation", "ElementInformation")
                        .WithOne("Element")
                        .HasForeignKey("DataAccess.Entities.Element", "ElementInformationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ElementInformation");
                });

            modelBuilder.Entity("DataAccess.Entities.Maintenance", b =>
                {
                    b.HasOne("DataAccess.Entities.Element", "Element")
                        .WithMany("Maintenances")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("DataAccess.Entities.OperationsProcess", b =>
                {
                    b.HasOne("DataAccess.Entities.CriticalValues", "CriticalValues")
                        .WithOne("OperationsProcess")
                        .HasForeignKey("DataAccess.Entities.OperationsProcess", "CriticalValuesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.OperationCondition", "OperationCondition")
                        .WithOne("OperationsProcess")
                        .HasForeignKey("DataAccess.Entities.OperationsProcess", "OperationConditionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.ProductionCondition", "ProductionCondition")
                        .WithOne("OperationsProcess")
                        .HasForeignKey("DataAccess.Entities.OperationsProcess", "ProductionConditionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.WoodType", "WoodType")
                        .WithMany("OperationsProcesses")
                        .HasForeignKey("WoodTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("DataAccess.Entities.ValueObjects.AuditTimestamp", "auditTimestamp", b1 =>
                        {
                            b1.Property<int>("OperationsProcessId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndAt");

                            b1.Property<DateTime>("StartAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartAt");

                            b1.HasKey("OperationsProcessId");

                            b1.ToTable("OperationsProcesses");

                            b1.WithOwner()
                                .HasForeignKey("OperationsProcessId");
                        });

                    b.Navigation("CriticalValues");

                    b.Navigation("OperationCondition");

                    b.Navigation("ProductionCondition");

                    b.Navigation("WoodType");

                    b.Navigation("auditTimestamp")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.CriticalValues", b =>
                {
                    b.Navigation("OperationsProcess")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Element", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("DataAccess.Entities.ElementInformation", b =>
                {
                    b.Navigation("Element")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.OperationCondition", b =>
                {
                    b.Navigation("OperationsProcess")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.ProductionCondition", b =>
                {
                    b.Navigation("OperationsProcess")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.WoodType", b =>
                {
                    b.Navigation("OperationsProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
